trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation - Docker Hub/ACR/...
  dockerRegistryServiceConnection: 'bfcbc9a8-079f-469d-889b-db8b10b4eb59'
  # Kubernetes service connection
  kubernetesServiceConnection: '5f552435-78fd-4ba0-b3ce-9d63384ca426'
  # Docker repository image full path
  imageRepositoryFullPath: 'aksdockersample/aks-docker-sample'
  # docker file path in the github repo
  dockerfilePath: 'dockerfile'  
  # Environment name
  # should we not have a way to mention this like $(DeployEnvironmentName) ?
  deployEnvironmentName: 'Madhuv-Play.default'
  # Kubernetes Namespace
  k8sNamespace: 'default'
  # kubernetes manifest file
  k8sManifests: 'DockerAKSTutorial/AKSDeployment.yaml'
  # Agent Pool Name
  poolName: 'Hosted Ubuntu 1604'

stages:
- stage: Deploy
  displayName: 'Deploy stage'
  # dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    # can not w euse variables?
    environment: 'Madhuv-Play.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'ls ; git clone https://github.com/madhuv-msft/DockerAKSTutorial.git .;'
              errorActionPreference: 'continue'
          - task: KubernetesManifest@0
            displayName: 'Deploy to Kubernetes cluster'
            inputs:
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              action: 'deploy'
              namespace: $(k8sNamespace)
              manifests: $(k8sManifests)
              containers: $(imageRepositoryFullPath):$(Build.BuildId)
